/**
 * SyncPad — Design Tokens: Colors
 *
 * Derived from the "Nocturne Glass" design system generated by Google Stitch.
 * All colors used throughout the app should reference these constants.
 */

export const colors = {
  // ─── Background & Surfaces ──────────────────────────────
  background: '#0c0c1d',
  surface: '#0c0c1d',
  surfaceDim: '#0c0c1d',
  surfaceBright: '#2a2a43',
  surfaceContainer: '#18182b',
  surfaceContainerLow: '#121223',
  surfaceContainerHigh: '#1d1d33',
  surfaceContainerHighest: '#24233b',
  surfaceContainerLowest: '#000000',
  surfaceVariant: '#24233b',
  surfaceTint: '#FFFFFF',

  // ─── Primary (Monochrome Obsidian) ──────────────────────
  primary: '#FFFFFF',
  primaryDim: '#E6E3FB',
  primaryContainer: '#2A2A43',
  primaryFixed: '#E6E3FB',
  primaryFixedDim: '#D1D0E0',
  onPrimary: '#000000',
  onPrimaryContainer: '#000000',
  onPrimaryFixed: '#000000',

  // ─── Secondary ──────────────────────────────────────────
  secondary: '#E6E3FB',
  secondaryDim: '#D1D0E0',
  secondaryContainer: '#1D1D33',
  secondaryFixed: '#E6E3FB',
  onSecondary: '#000000',
  onSecondaryContainer: '#FFFFFF',

  // ─── Tertiary (Accent) ─────────────────────────────────
  tertiary: '#FF9DD0',
  tertiaryDim: '#EB7BB8',
  tertiaryContainer: '#FB88C6',
  onTertiary: '#6C0F4C',

  // ─── Error ──────────────────────────────────────────────
  error: '#FF6E84',
  errorDim: '#D73357',
  errorContainer: '#A70138',
  onError: '#490013',
  onErrorContainer: '#FFB2B9',

  // ─── Text / On Surface ─────────────────────────────────
  onBackground: '#E6E3FB',
  onSurface: '#E6E3FB',
  onSurfaceVariant: '#ABA9BF',

  // ─── Outline ────────────────────────────────────────────
  outline: '#757388',
  outlineVariant: '#474659',

  // ─── Inverse ────────────────────────────────────────────
  inverseSurface: '#FCF8FF',
  inverseOnSurface: '#545366',
  inversePrimary: '#FFFFFF',


  // ─── Semantic ───────────────────────────────────────────
  success: '#00D68F',
  warning: '#FFB800',
  info: '#00D4FF',
} as const;

/**
 * Collaboration cursor colors — each user gets a unique color from this palette
 */
export const collaborationColors = [
  '#a8a4ff', // primary purple
  '#ff9dd0', // pink
  '#00D68F', // green
  '#00D4FF', // cyan
  '#FFB800', // amber
  '#FF6B6B', // coral
  '#8B83FF', // light purple
  '#eb7bb8', // rose
  '#675df9', // indigo
  '#9891ff', // lavender
  '#ff6e84', // salmon
  '#d73357', // crimson
] as const;

export type ColorToken = keyof typeof colors;
