/**
 * SyncPad — Design Tokens: Colors
 *
 * Derived from the "Nocturne Glass" design system generated by Google Stitch.
 * All colors used throughout the app should reference these constants.
 */

export const colors = {
  // ─── Background & Surfaces ──────────────────────────────
  background: '#0c0c1d',
  surface: '#0c0c1d',
  surfaceDim: '#0c0c1d',
  surfaceBright: '#2a2a43',
  surfaceContainer: '#18182b',
  surfaceContainerLow: '#121223',
  surfaceContainerHigh: '#1d1d33',
  surfaceContainerHighest: '#24233b',
  surfaceContainerLowest: '#000000',
  surfaceVariant: '#24233b',
  surfaceTint: '#a8a4ff',

  // ─── Primary ────────────────────────────────────────────
  primary: '#a8a4ff',
  primaryDim: '#675df9',
  primaryContainer: '#9995ff',
  primaryFixed: '#9995ff',
  primaryFixedDim: '#8a85ff',
  onPrimary: '#1e009f',
  onPrimaryContainer: '#16007d',
  onPrimaryFixed: '#000000',

  // ─── Secondary ──────────────────────────────────────────
  secondary: '#9891ff',
  secondaryDim: '#9891ff',
  secondaryContainer: '#3d31ad',
  secondaryFixed: '#d1ccff',
  onSecondary: '#160074',
  onSecondaryContainer: '#cfcbff',

  // ─── Tertiary (Accent) ─────────────────────────────────
  tertiary: '#ff9dd0',
  tertiaryDim: '#eb7bb8',
  tertiaryContainer: '#fb88c6',
  onTertiary: '#6c0f4c',

  // ─── Error ──────────────────────────────────────────────
  error: '#ff6e84',
  errorDim: '#d73357',
  errorContainer: '#a70138',
  onError: '#490013',
  onErrorContainer: '#ffb2b9',

  // ─── Text / On Surface ─────────────────────────────────
  onBackground: '#e6e3fb',
  onSurface: '#e6e3fb',
  onSurfaceVariant: '#aba9bf',

  // ─── Outline ────────────────────────────────────────────
  outline: '#757388',
  outlineVariant: '#474659',

  // ─── Inverse ────────────────────────────────────────────
  inverseSurface: '#fcf8ff',
  inverseOnSurface: '#545366',
  inversePrimary: '#5044e3',

  // ─── Semantic ───────────────────────────────────────────
  success: '#00D68F',
  warning: '#FFB800',
  info: '#00D4FF',
} as const;

/**
 * Collaboration cursor colors — each user gets a unique color from this palette
 */
export const collaborationColors = [
  '#a8a4ff', // primary purple
  '#ff9dd0', // pink
  '#00D68F', // green
  '#00D4FF', // cyan
  '#FFB800', // amber
  '#FF6B6B', // coral
  '#8B83FF', // light purple
  '#eb7bb8', // rose
  '#675df9', // indigo
  '#9891ff', // lavender
  '#ff6e84', // salmon
  '#d73357', // crimson
] as const;

export type ColorToken = keyof typeof colors;
